from XL_Giao_Tiep.Giao_Tiep_Nhan_Vien import Giao_Tiep_Nhan_Vien
from XL_Giao_Tiep.Giao_Tiep_Phim import Giao_Tiep_Phim
from XL_Giao_Tiep.Giao_Tiep_Xuat_Chieu import Giao_Tiep_Xuat_Chieu
from XL_Giao_Tiep.Giao_Tiep_Ve import Giao_Tiep_Ve
from XL_Giao_Tiep.Giao_Tiep_Ghe import Giao_Tiep_Ghe
from XL_Giao_Tiep.Giao_Tiep_Phong import Giao_Tiep_Phong
from XL_Giao_Tiep.Giao_Tiep_Loai_Phong import Giao_Tiep_Loai_Phong
from XL_Giao_Tiep.Giao_Tiep_Rap import Giao_Tiep_Rap

